import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";
//import { Inter } from 'next/font/google';
// import { useTranslation } from 'next-i18next';
import Link from 'next/link'
import { getProfileWithNameAndID } from "../../../services";
//import {NextIntlClientProvider, useMessages} from 'next-intl';

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: string; id: string };
}) {
  const { locale } = await params; // 修正: awaitを削除
  const profiles = await getProfileWithNameAndID(locale); // サーバーで直接データ取得

  return (
    <html lang={locale}>
      <body>
        <nav>
          <Link key="home" href="/">Home</Link>
          {profiles.map((profile, index) => (
            <Link key={index} href={`/${locale}/family/${profile._id}`}>
              {profile.name}
            </Link>
          ))}
        </nav>
        {children}
      </body>
    </html>
  );
}
