import type { Metadata } from "next";
import Link from 'next/link'
import { getProfileWithNameAndID } from "../../../services";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: string; id: string };
}) {
  const { locale } = await params; // 修正: awaitを削除
  const profiles = await getProfileWithNameAndID(locale); // サーバーで直接データ取得

  return (
    <html lang={locale}>
      <body>
        <nav>
          <Link key="home" href="/">Home</Link>
          {profiles.map((profile, index) => (
            <Link key={index} href={`/${locale}/family/${profile._id}/`}>
              {profile.name}
            </Link>
          ))}
        </nav>
        {children}
      </body>
    </html>
  );
}

