import type { Metadata } from "next";
import Link from 'next/link'
import { getProfileWithNameAndID } from "../../../services";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{ locale: string; id: string }>;
}) {
  const resolvedParams = await props.params; // `params` を `await` してから使う
  const { locale } = await resolvedParams; // localeを取得
  const profiles = await getProfileWithNameAndID(locale); // サーバーで直接データ取得

  return (
      <>
        <nav>
          <Link key="home" href="/">Home</Link>
          {profiles.map((profile, index) => (
            <Link key={index} href={`/${locale}/family/${profile._id}/`}>
              {profile.name}
            </Link>
          ))}
        </nav>
        {props.children}
      </>
  );
}

