import type { Metadata } from "next";
import "../globals.css";
import Link from 'next/link'
import { getProfiles } from "../services";
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = params;
  const profiles = await getProfiles(locale); // サーバーで直接データ取得

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <nav className="d-flex justify-content-between align-items-center p-3 bg-light">
          <div>
            <Link key="home" href="/" className="me-3">Home</Link>
            {profiles.map((profile, index) => (
              <Link key={index} href={`/${locale}/family/${profile._id}`} className="me-3">
                {profile.name}
              </Link>
            ))}
          </div>

          {/* Registration ボタンを追加 */}
          <Link href={`/${locale}/submit`}>
            <button className="btn btn-primary">Registration</button>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
