# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at 00:00 UTC

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run dependabot
        uses: dependabot/dependabot-core@v2
        with:
          package-ecosystem: "" # See documentation for possible values
          directory: "/" # Location of package manifests
          schedule-interval: "weekly"
